

vlogan +v2k  "/home/srdejong/THDB_Demo_Reconstruction/lpm_pll_sim/lpm_pll.vo"                                 
vhdlan -xlrm "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/dspba_library_package.vhd"                      
vhdlan -xlrm "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/dspba_library.vhd"                              
vhdlan -xlrm "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/auk_dspip_math_pkg_hpfir.vhd"                   
vhdlan -xlrm "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/auk_dspip_lib_pkg_hpfir.vhd"                    
vhdlan -xlrm "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/auk_dspip_avalon_streaming_controller_hpfir.vhd"
vhdlan -xlrm "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/auk_dspip_avalon_streaming_sink_hpfir.vhd"      
vhdlan -xlrm "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/auk_dspip_avalon_streaming_source_hpfir.vhd"    
vhdlan -xlrm "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/auk_dspip_roundsat_hpfir.vhd"                   
vlogan +v2k  "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/altera_avalon_sc_fifo.v"                        
vhdlan -xlrm "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/FIR_rtl_core.vhd"                               
vhdlan -xlrm "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/FIR_ast.vhd"                                    
vhdlan -xlrm "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/FIR.vhd"                                        
vhdlan -xlrm "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/FIR_tb.vhd"                                     
