

vlog "/home/srdejong/THDB_Demo_Reconstruction/lpm_pll_sim/lpm_pll.vo"                                 
vcom "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/dspba_library_package.vhd"                      
vcom "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/dspba_library.vhd"                              
vcom "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/auk_dspip_math_pkg_hpfir.vhd"                   
vcom "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/auk_dspip_lib_pkg_hpfir.vhd"                    
vcom "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/auk_dspip_avalon_streaming_controller_hpfir.vhd"
vcom "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/auk_dspip_avalon_streaming_sink_hpfir.vhd"      
vcom "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/auk_dspip_avalon_streaming_source_hpfir.vhd"    
vcom "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/auk_dspip_roundsat_hpfir.vhd"                   
vlog "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/altera_avalon_sc_fifo.v"                        
vcom "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/FIR_rtl_core.vhd"                               
vcom "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/FIR_ast.vhd"                                    
vcom "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/FIR.vhd"                                        
vcom "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/FIR_tb.vhd"                                     
