

ncvlog      "/home/srdejong/THDB_Demo_Reconstruction/lpm_pll_sim/lpm_pll.vo"                                 
ncvhdl -v93 "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/dspba_library_package.vhd"                      
ncvhdl -v93 "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/dspba_library.vhd"                              
ncvhdl -v93 "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/auk_dspip_math_pkg_hpfir.vhd"                   
ncvhdl -v93 "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/auk_dspip_lib_pkg_hpfir.vhd"                    
ncvhdl -v93 "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/auk_dspip_avalon_streaming_controller_hpfir.vhd"
ncvhdl -v93 "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/auk_dspip_avalon_streaming_sink_hpfir.vhd"      
ncvhdl -v93 "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/auk_dspip_avalon_streaming_source_hpfir.vhd"    
ncvhdl -v93 "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/auk_dspip_roundsat_hpfir.vhd"                   
ncvlog      "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/altera_avalon_sc_fifo.v"                        
ncvhdl -v93 "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/FIR_rtl_core.vhd"                               
ncvhdl -v93 "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/FIR_ast.vhd"                                    
ncvhdl -v93 "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/FIR.vhd"                                        
ncvhdl -v93 "/home/srdejong/THDB_Demo_Reconstruction/FIR_sim/FIR_tb.vhd"                                     
